### ISSUE TITLE
Database credentials are not passed correctly

### ISSUE THREAD

**Issue by dsferruzza** [zileo-net/clevercloud-keycloak#3]
Hi!
Thanks for sharing this repo!

Passing database credentials using `KC_DB_URL="jdbc:${POSTGRESQL_ADDON_HOST}"` did not work for me (I'm not sure how it is supposed to get the username/password for example).
Neither did using `KC_DB_URL="jdbc:${POSTGRESQL_ADDON_URI}"` (I guess username/password are not supposed to be passed this way).

I had to do the following to make it work:

```bash
export KC_DB_URL="jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}"
export KC_DB_USERNAME="$POSTGRESQL_ADDON_USER"
export KC_DB_PASSWORD="$POSTGRESQL_ADDON_PASSWORD"
```

**Comment by jlannoy** [comment]
You were right, the last changes was breaking how it should work. I cleaned it up.
